server:
  port: 8181

msa:
  clients:
    jwt:
      baseUrl: http://localhost:8182
    user:
      baseUrl: http://localhost:8183

logging:
  pattern.console: '%white([%thread]) %highlight(%-5level) %cyan(%logger{5}) %magenta([%file:%-4L]) - %msg%n'
  level:
    root: INFO
