version: "3.8"

services:
  mongodb:
    image: mongo:3
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - smart-link-network

  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    image: smart-link/auth:latest
    restart: on-failure
    ports:
      - "8181:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - smart-link-network

  editor:
    depends_on:
      - mongodb
    build:
      context: editor
      dockerfile: Dockerfile
    image: smart-link/editor:latest
    restart: on-failure
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - smart-link-network

  jwt:
    build:
      context: jwt
      dockerfile: Dockerfile
    image: smart-link/jwt:latest
    restart: on-failure
    ports:
      - "8182:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - smart-link-network

  user:
    build:
      context: user
      dockerfile: Dockerfile
    image: smart-link/user:latest
    restart: on-failure
    ports:
      - "8183:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - smart-link-network

  service:
    build:
      context: service
      dockerfile: Dockerfile
    image: smart-link/service:latest
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - smart-link-network

volumes:
  mongo_data: { }

networks:
  smart-link-network:
    driver: bridge
