server:
  port: 8081

msa:
  clients:
    jwt:
      baseUrl: http://localhost:8182
    editor:
      baseUrl: http://localhost:8082

logging:
  pattern.console: '%white([%thread]) %highlight(%-5level) %cyan(%logger{5}) %magenta([%file:%-4L]) - %msg%n'
  level:
    root: INFO
